name: Lint and build server

on:
  pull_request:
    branches: ['master']
    paths: [ '.github/workflows/lint-and-build-server.yml', 'web/server/**' ]

jobs:
  lint:
    name: Lint server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/server
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: web/server/package-lock.json

      - name: Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    name: Build server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/server
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: web/server/package-lock.json

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build
